
title: Dark Noise
email: charlie@darknoise.app
description: >- # this means to ignore newlines until "baseurl:"
  The official site of the Dark Noise app for iPhone, iPad, and Mac.
url: "https://darknoise.app"

twitter:
  username: DarkNoiseApp
  card: summary

social:
  name: Dark Noise
  links:
    - https://twitter.com/DarkNoiseApp



collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "pages"
    values:
      permalink: /:basename:output_ext

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
